### ISSUE TITLE
HMC Problem

### ISSUE THREAD

**Issue by ni-phy** [ni-phy/year4-project#4]
Hi @grd349 

I'm having issues with sampling. The error I get is: 

`parameters` should only contain gpflow.Parameter objects with priors

The problem seems to originate from gpflow.optimizers.SamplingHelper (line 63 in gyro-2d-hmc.py).The strange thing is that when printing the model.trainable_parameters they all seem to have prior values. I tried running the code with a random function as the hmc_helper and it worked fine. I also tried changing kernels/means, setting the parameters manually as trainable and defining manually the priors but still no luck. Any ideas?

**Comment by grd349** [comment]
Sorry - that's not something I have seen before.  Here are my suggestions on how to proceed if you have not tried these already:

- Shut everything down, reboot, and try again.  Sometimes this works.
- Debug ... build the smallest, simplest possible model and see if the problem persists.  If the problem goes away, add things one-by-one till it breaks.  Then you know where the problem is.
- Search on stackoverflow.com for similar problems.
- Post on stackoverflow.com and see if someone else knows the answer.
